# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
"""Paper (RA-L) figure/table pipeline -- pure post-processing, no Isaac Sim, no GPU.

Reads already-computed summary.json / eval outputs from the experiments tree and
renders single-column RA-L-style PDF+PNG figures plus CSV/LaTeX tables. Reuses the
existing sim-free engine (`_analyze.recompute_metrics.floor_verdict`/`unit_for`,
DR_LEVELS/DR_SCALE) for all metric math -- this script only assembles + renders,
it recomputes nothing eval.py or compare.py already computes correctly (avoids the
three-drifted-implementations trap documented in recompute_metrics.py).

Run from the repo root with plain python3 (matplotlib/numpy only):
    python3 tools/paper_figures.py all
    python3 tools/paper_figures.py fault-ablation
    python3 tools/paper_figures.py teacher-summary
    python3 tools/paper_figures.py doraemon-curriculum
    python3 tools/paper_figures.py student-comparison

Each figure's output directory is the SSOT run's own `analysis/paper_figures/`
(never a new top-level location) and gets a manifest.json recording source
summary.json paths (+ sha256), the figures/tables produced, and any caveats
(e.g. single-seed screening) -- so a reader can trace every number back to disk.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

REPO_ROOT = os.getcwd()
_ANALYSIS_DIR = os.path.join(REPO_ROOT, "constrained_albc", "analysis")
if _ANALYSIS_DIR not in sys.path:
    sys.path.insert(0, _ANALYSIS_DIR)

from _analyze.recompute_metrics import AXIS_UNITS, DECISION_FLOORS, floor_verdict, unit_for  # noqa: E402
from common import DR_LEVELS  # noqa: E402

# ---------------------------------------------------------------------------
# RA-L (IEEE Robotics and Automation Letters) single-column figure defaults.
# Journal is two-column; single-column width = 3.45in (~88mm), serif body font.
# ---------------------------------------------------------------------------
RAL_RC = {
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Nimbus Roman", "Times", "DejaVu Serif"],
    "font.size": 8,
    "axes.titlesize": 9,
    "axes.labelsize": 8,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "legend.fontsize": 7,
    "axes.linewidth": 0.6,
    "lines.linewidth": 1.0,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "pdf.fonttype": 42,  # embed as real fonts, not Type 3 bitmaps
    "figure.figsize": (3.45, 2.4),
}
DR_LEVEL_COLORS = {"none": "#4C72B0", "soft": "#55A868", "medium": "#DD8452", "hard": "#C44E52"}
ARM_COLORS = ["#4C72B0", "#DD8452", "#55A868", "#8172B2"]


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO_ROOT, capture_output=True, text=True, timeout=5
        ).stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def _load_summary(path: str) -> dict:
    if not os.path.isfile(path):
        raise FileNotFoundError(f"summary.json not found: {path}")
    with open(path) as f:
        return json.load(f)


def _val(summary: dict, lvl: str, axis: str, field: str):
    return summary.get(lvl, {}).get(axis, {}).get(field)


def _write_manifest(out_dir: str, source_files: list[str], outputs: list[str], caveats: list[str], extra: dict | None = None) -> str:
    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "tools/paper_figures.py",
        "argv": sys.argv,
        "git_sha": _git_sha(),
        "source_files": [{"path": p, "sha256": _sha256(p)} for p in source_files],
        "outputs": outputs,
        "caveats": caveats,
    }
    if extra:
        manifest.update(extra)
    path = os.path.join(out_dir, "manifest.json")
    with open(path, "w") as f:
        json.dump(manifest, f, indent=2)
    return path


def _write_csv(path: str, header: list[str], rows: list[list]) -> None:
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)


def _write_latex_table(path: str, caption: str, label: str, header: list[str], rows: list[list], col_align: str | None = None) -> None:
    ncols = len(header)
    align = col_align or ("l" + "r" * (ncols - 1))
    lines = [
        r"% auto-generated by tools/paper_figures.py -- do not hand-edit, regenerate instead",
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        rf"\begin{{tabular}}{{{align}}}",
        r"\toprule",
        " & ".join(header) + r" \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(str(c) for c in row) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def _savefig(fig, out_dir: str, stem: str) -> list[str]:
    png = os.path.join(out_dir, f"{stem}.png")
    pdf = os.path.join(out_dir, f"{stem}.pdf")
    fig.savefig(png, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)
    return [os.path.basename(png), os.path.basename(pdf)]


# ---------------------------------------------------------------------------
# T12 -- fault_dr ablation: anchor vs Arm A (agnostic) vs Arm B (privileged),
# m4-dead minus healthy delta on att_norm ss_error, all 4 DR levels.
#
# NOTE: this is the anchor/A/B trio (E4-2/3/4 in container-verifications.md),
# NOT the E-ftc1 severity-head-start run (E4-1) -- that run's own wiki entry
# ("severity_init_head_start_converts_to_curriculum...") tags it explicitly
# [CAVEAT] "Single seed (30), paired screening; never a paper number" and it
# is excluded from this figure for that reason.
# ---------------------------------------------------------------------------
FAULT_ABLATION_RUN_DIR = "experiments/rsl_rl/albc_trpo_teacher/fault_dr/trpo_faultdr_agnostic_s30_260725_183121"
FAULT_ABLATION_ARMS = [
    (
        "anchor",
        "experiments/rsl_rl/albc_trpo_teacher/teacher_baseline_buoyfix/trpo_buoyanchor_s30_260722_134743/eval/static_260725_164839/summary.json",
        "experiments/rsl_rl/albc_trpo_teacher/teacher_baseline_buoyfix/trpo_buoyanchor_s30_260722_134743/eval/static_260725_165657/summary.json",
    ),
    (
        "Arm A (agnostic)",
        "experiments/rsl_rl/albc_trpo_teacher/fault_dr/trpo_faultdr_agnostic_s30_260725_183121/eval/static_260727_124731/summary.json",
        "experiments/rsl_rl/albc_trpo_teacher/fault_dr/trpo_faultdr_agnostic_s30_260725_183121/eval/static_260727_125603/summary.json",
    ),
    (
        "Arm B (privileged)",
        "experiments/rsl_rl/albc_trpo_teacher/fault_dr/trpo_faultdr_priv_s30_260725_232149/eval/static_260727_123908/summary.json",
        "experiments/rsl_rl/albc_trpo_teacher/fault_dr/trpo_faultdr_priv_s30_260725_232149/eval/static_260727_130536/summary.json",
    ),
]


def cmd_fault_ablation(_args: argparse.Namespace) -> None:
    out_dir = os.path.join(FAULT_ABLATION_RUN_DIR, "analysis", "paper_figures")
    os.makedirs(out_dir, exist_ok=True)

    axis, field = "att_norm", "ss_error"
    floor = DECISION_FLOORS[field]
    source_files = []
    # {arm_label: {level: (delta, verdict)}}
    results: dict[str, dict[str, tuple[float, str]]] = {}
    for label, healthy_path, dead_path in FAULT_ABLATION_ARMS:
        source_files += [healthy_path, dead_path]
        healthy, dead = _load_summary(healthy_path), _load_summary(dead_path)
        per_level = {}
        for lvl in DR_LEVELS:
            h, d = _val(healthy, lvl, axis, field), _val(dead, lvl, axis, field)
            if h is None or d is None:
                per_level[lvl] = (float("nan"), "NO-FLOOR")
                continue
            delta = float(d) - float(h)
            per_level[lvl] = (delta, floor_verdict(field, delta, axis))
        results[label] = per_level

    # -- figure: grouped bars, delta att_norm ss_error (deg) per DR level per arm --
    with plt.rc_context(RAL_RC):
        fig, ax = plt.subplots(figsize=(3.45, 2.5))
        n_arms = len(FAULT_ABLATION_ARMS)
        x = np.arange(len(DR_LEVELS))
        width = 0.8 / n_arms
        for i, (label, _, _) in enumerate(FAULT_ABLATION_ARMS):
            deltas = [results[label][lvl][0] for lvl in DR_LEVELS]
            ax.bar(x + (i - (n_arms - 1) / 2) * width, deltas, width, label=label, color=ARM_COLORS[i])
        ax.axhline(floor, color="0.4", linestyle="--", linewidth=0.7, label=f"screening floor ({floor:g}°)")
        ax.set_xticks(x)
        ax.set_xticklabels(DR_LEVELS)
        ax.set_ylabel(f"Δ att_norm ss_error [{unit_for(axis, field)}]\n(m4-dead − healthy)")
        ax.set_xlabel("DR level")
        ax.legend(loc="upper left", frameon=False)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        outputs = _savefig(fig, out_dir, "fault_dr_ablation")

    # -- table: CSV + LaTeX --
    header = ["DR level"] + [label for label, _, _ in FAULT_ABLATION_ARMS]
    rows = []
    for lvl in DR_LEVELS:
        row = [lvl]
        for label, _, _ in FAULT_ABLATION_ARMS:
            delta, verdict = results[label][lvl]
            mark = "" if verdict == "REAL" else " (below floor)"
            row.append(f"{delta:+.3f}{mark}")
        rows.append(row)
    csv_path = os.path.join(out_dir, "fault_dr_ablation.csv")
    _write_csv(csv_path, header, rows)
    tex_rows = []
    for lvl in DR_LEVELS:
        row = [lvl]
        for label, _, _ in FAULT_ABLATION_ARMS:
            delta, verdict = results[label][lvl]
            cell = f"{delta:+.3f}"
            if verdict != "REAL":
                cell += r"$^{\dagger}$"
            row.append(cell)
        tex_rows.append(row)
    tex_path = os.path.join(out_dir, "fault_dr_ablation.tex")
    _write_latex_table(
        tex_path,
        caption=(
            r"Fault-tolerance ablation: $\Delta$ attitude-norm steady-state error "
            r"(m4-dead $-$ healthy, degrees) across DR levels. "
            r"$^{\dagger}$below the 0.10\textdegree{} screening floor (noise, single seed)."
        ),
        label="tab:fault_dr_ablation",
        header=header,
        rows=tex_rows,
    )
    outputs += [os.path.basename(csv_path), os.path.basename(tex_path)]

    manifest_path = _write_manifest(
        out_dir,
        source_files,
        outputs,
        caveats=[
            "n=1 (single seed 30) per arm; REAL/BELOW-FLOOR verdicts use the workspace's "
            "pre-registered screening floors (_analyze/recompute_metrics.DECISION_FLOORS), "
            "not a statistical test.",
            "E-ftc1 (severity-head-start run) intentionally excluded -- its own wiki entry "
            "flags it 'never a paper number' (single-seed screening only).",
        ],
        extra={"axis": axis, "field": field, "floor_deg": floor},
    )
    print(f"[fault-ablation] wrote {len(outputs)} files to {out_dir}")
    print(f"[fault-ablation] manifest: {manifest_path}")


# ---------------------------------------------------------------------------
# T10 -- final teacher performance summary: incumbent (model_9998) vs the two
# reproducibility-check seeds R30/R31 that were run to decide whether to
# replace it. att_norm ss_error, all 4 DR levels (the decision axis used in
# teacher_final_replicate's own report.md).
# ---------------------------------------------------------------------------
TEACHER_SUMMARY_RUN_DIR = "experiments/rsl_rl/albc_trpo_teacher/teacher_final_replicate/trpo_replicate_s30_260810_140415"
TEACHER_SUMMARY_ARMS = [
    ("incumbent (model_9998)", "experiments/rsl_rl/albc_trpo_teacher/teacher_iter_budget/trpo_iterbudget_s30_260805_012813/eval/static_260814_234643/summary.json"),
    ("R30 (seed 30 replicate)", "experiments/rsl_rl/albc_trpo_teacher/teacher_final_replicate/trpo_replicate_s30_260810_140415/eval/static_260814_232725/summary.json"),
    ("R31 (seed 31 replicate)", "experiments/rsl_rl/albc_trpo_teacher/teacher_final_replicate/trpo_replicate_s31_260810_140414_dgxcopy/eval/static_260814_233603/summary.json"),
]


def cmd_teacher_summary(_args: argparse.Namespace) -> None:
    out_dir = os.path.join(TEACHER_SUMMARY_RUN_DIR, "analysis", "paper_figures")
    os.makedirs(out_dir, exist_ok=True)

    axis, field = "att_norm", "ss_error"
    source_files = [p for _, p in TEACHER_SUMMARY_ARMS]
    # {arm_label: {level: value}}
    results: dict[str, dict[str, float]] = {}
    for label, path in TEACHER_SUMMARY_ARMS:
        s = _load_summary(path)
        results[label] = {lvl: _val(s, lvl, axis, field) for lvl in DR_LEVELS}

    with plt.rc_context(RAL_RC):
        fig, ax = plt.subplots(figsize=(3.45, 2.5))
        n_arms = len(TEACHER_SUMMARY_ARMS)
        x = np.arange(len(DR_LEVELS))
        width = 0.8 / n_arms
        for i, (label, _) in enumerate(TEACHER_SUMMARY_ARMS):
            vals = [results[label][lvl] for lvl in DR_LEVELS]
            ax.bar(x + (i - (n_arms - 1) / 2) * width, vals, width, label=label, color=ARM_COLORS[i])
        ax.set_xticks(x)
        ax.set_xticklabels(DR_LEVELS)
        ax.set_ylabel(f"att_norm ss_error [{unit_for(axis, field)}]")
        ax.set_xlabel("DR level")
        ax.legend(loc="upper left", frameon=False, fontsize=6)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        outputs = _savefig(fig, out_dir, "teacher_final_summary")

    header = ["DR level"] + [label for label, _ in TEACHER_SUMMARY_ARMS]
    rows = [[lvl] + [f"{results[label][lvl]:.4f}" for label, _ in TEACHER_SUMMARY_ARMS] for lvl in DR_LEVELS]
    csv_path = os.path.join(out_dir, "teacher_final_summary.csv")
    _write_csv(csv_path, header, rows)
    tex_path = os.path.join(out_dir, "teacher_final_summary.tex")
    _write_latex_table(
        tex_path,
        caption=(
            "Final teacher selection: attitude-norm steady-state tracking error "
            r"(degrees, lower is better) for the deployed incumbent (\texttt{model\_9998}) "
            "against two from-scratch reproducibility-check seeds. The incumbent was "
            "retained -- neither seed beats it at the decision (hard) level."
        ),
        label="tab:teacher_final_summary",
        header=header,
        rows=rows,
    )
    outputs += [os.path.basename(csv_path), os.path.basename(tex_path)]

    manifest_path = _write_manifest(
        out_dir,
        source_files,
        outputs,
        caveats=[
            "3-way comparison, n=1 per arm (screening protocol, not a statistical test).",
            "R30/R31 are from-scratch reproducibility-check runs at the incumbent's config, "
            "not independent architectural alternatives -- see "
            "teacher_final_replicate/.../analysis/diagnose-20260814-235911/report.md §0/§7.",
        ],
        extra={"axis": axis, "field": field},
    )
    print(f"[teacher-summary] wrote {len(outputs)} files to {out_dir}")
    print(f"[teacher-summary] manifest: {manifest_path}")


# ---------------------------------------------------------------------------
# F2/T4 -- DORAEMON curriculum: wrap the existing analyze_training.py --deep
# output (05_doraemon_curriculum.png) into RA-L single-column PDF+PNG. Does
# NOT recompute the curriculum (that engine is GPU/Isaac-free but its own,
# tested tool -- .omx/profile/analyze_training.py); this only re-renders the
# already-produced raster into the paper's format.
# ---------------------------------------------------------------------------
DORAEMON_RUN_DIR = "experiments/rsl_rl/albc_trpo_teacher/teacher_iter_budget/trpo_iterbudget_s30_260805_012813"


def cmd_doraemon_curriculum(args: argparse.Namespace) -> None:
    # analyze_training.py writes into the run's LOGS-side analysis/ dir (heavy,
    # tied to the raw TB event data), reached from the light experiments/ index
    # tree only via the `train` symlink -- NOT experiments/<run>/analysis/,
    # which is exp-analyze's own diagnose-*/ report location (a different dir).
    src_png = os.path.join(DORAEMON_RUN_DIR, "train", "analysis", "05_doraemon_curriculum.png")
    if not os.path.isfile(src_png):
        if not args.generate_if_missing:
            print(f"[doraemon-curriculum] SKIPPED: {src_png} not found. "
                  f"Re-run with --generate-if-missing to invoke analyze_training.py --deep "
                  f"(needs /isaac-sim/python.sh, not plain python3).")
            return
        print(f"[doraemon-curriculum] {src_png} missing, invoking analyze_training.py --deep ...")
        train_dir = os.path.join(DORAEMON_RUN_DIR, "train")
        subprocess.run(
            ["/isaac-sim/python.sh", ".omx/profile/analyze_training.py", train_dir, "--deep", "--tier", "1"],
            cwd=REPO_ROOT, check=True,
        )
        if not os.path.isfile(src_png):
            raise FileNotFoundError(f"analyze_training.py ran but {src_png} still missing")

    out_dir = os.path.join(DORAEMON_RUN_DIR, "analysis", "paper_figures")
    os.makedirs(out_dir, exist_ok=True)

    img = plt.imread(src_png)
    h, w = img.shape[0], img.shape[1]
    with plt.rc_context(RAL_RC):
        # RA-L single column width; this source panel is a wide multi-panel
        # dashboard, so render at 2x single-column width (still fits a
        # \figure*-style spanning placement, or the LaTeX side can \resizebox
        # it back down) rather than shrinking text below legibility.
        fig_w = 7.16  # IEEE double-column width (in)
        fig_h = fig_w * h / w
        fig, ax = plt.subplots(figsize=(fig_w, fig_h))
        ax.imshow(img)
        ax.axis("off")
        outputs = _savefig(fig, out_dir, "doraemon_curriculum")

    csv_note_path = None  # no tabular data here, figure-only
    manifest_path = _write_manifest(
        out_dir,
        [src_png],
        outputs,
        caveats=[
            "This is a re-rendered copy of the existing analyze_training.py --deep output "
            "(curriculum band math is NOT recomputed here); source pixels are unchanged, "
            "only the container format/size changed for print placement.",
        ],
        extra={"source_tool": ".omx/profile/analyze_training.py --deep --tier 1", "source_png": src_png},
    )
    print(f"[doraemon-curriculum] wrote {len(outputs)} files to {out_dir}")
    print(f"[doraemon-curriculum] manifest: {manifest_path}")


# ---------------------------------------------------------------------------
# T11/E1 -- student TCN vs GRU deployment comparison, with the model_9998
# teacher run (already used as the "incumbent" arm in teacher-summary, T10)
# included as a full-state anchor. E1 (findings/eval-diag.md, 2026-08-23)
# resolved the earlier "eval.py hangs" misdiagnosis -- it was stdout
# full-buffering on a redirected log, not a real stall; both students and
# the teacher control ran to completion once PYTHONUNBUFFERED=1 replaced the
# log-silence kill heuristic. Each candidate's *latest* summary.json (highest
# static_<ts> eval dir that actually wrote one -- partial/killed dirs from
# the pre-fix attempts have no summary.json and sort out automatically) is
# used, so this never needs manual path updates on re-run.
# ---------------------------------------------------------------------------
STUDENT_COMPARISON_RUN_DIR = "experiments/rsl_rl/albc_trpo_student/student_final_round"
STUDENT_COMPARISON_CANDIDATES = [
    ("TCN", "experiments/rsl_rl/albc_trpo_student/student_final_round/trpo_sdfinal_tcn_select_inc9998_s30_260810_160551"),
    ("GRU/C3", "experiments/rsl_rl/albc_trpo_student/student_final_round/trpo_sdfinal_c3_gruselect_inc9998_s30_260810_124813"),
]
# Teacher anchor: full-state (non-partial-obs, no encoder) policy, same
# checkpoint and same summary.json already cited by teacher-summary (T10) --
# reused rather than re-run so both figures point at one source file.
STUDENT_COMPARISON_ANCHOR = (
    "teacher (model_9998, full-state)",
    "experiments/rsl_rl/albc_trpo_teacher/teacher_iter_budget/trpo_iterbudget_s30_260805_012813/eval/static_260814_234643/summary.json",
)


def _latest_summary(run_dir: str) -> str | None:
    eval_dir = os.path.join(run_dir, "eval")
    if not os.path.isdir(eval_dir):
        return None
    summaries = [
        cand for sub in sorted(os.listdir(eval_dir))
        if os.path.isfile(cand := os.path.join(eval_dir, sub, "summary.json"))
    ]
    return summaries[-1] if summaries else None


def cmd_student_comparison(_args: argparse.Namespace) -> None:
    arms: list[tuple[str, str]] = []
    missing = []
    for label, run_dir in STUDENT_COMPARISON_CANDIDATES:
        summary_path = _latest_summary(run_dir)
        if summary_path is None:
            missing.append(label)
        else:
            arms.append((label, summary_path))
    if missing:
        print(f"[student-comparison] SKIPPED (T11/E1): no eval summary.json for {missing}. "
              f"Nothing written.")
        return
    arms.append(STUDENT_COMPARISON_ANCHOR)

    out_dir = os.path.join(STUDENT_COMPARISON_RUN_DIR, "analysis", "paper_figures")
    os.makedirs(out_dir, exist_ok=True)

    axis, field = "att_norm", "ss_error"
    source_files = [p for _, p in arms]
    # {arm_label: {level: value}}
    results: dict[str, dict[str, float]] = {}
    survival: dict[str, dict[str, float]] = {}
    for label, path in arms:
        s = _load_summary(path)
        results[label] = {lvl: _val(s, lvl, axis, field) for lvl in DR_LEVELS}
        survival[label] = {lvl: s.get(lvl, {}).get("survival_pct") for lvl in DR_LEVELS}

    with plt.rc_context(RAL_RC):
        fig, ax = plt.subplots(figsize=(3.45, 2.5))
        n_arms = len(arms)
        x = np.arange(len(DR_LEVELS))
        width = 0.8 / n_arms
        for i, (label, _) in enumerate(arms):
            vals = [results[label][lvl] for lvl in DR_LEVELS]
            ax.bar(x + (i - (n_arms - 1) / 2) * width, vals, width, label=label, color=ARM_COLORS[i])
        ax.set_xticks(x)
        ax.set_xticklabels(DR_LEVELS)
        ax.set_ylabel(f"att_norm ss_error [{unit_for(axis, field)}]")
        ax.set_xlabel("DR level")
        ax.legend(loc="upper left", frameon=False, fontsize=6)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.text(0.99, 0.02, "n=1 (seed 42)", transform=ax.transAxes,
                 ha="right", va="bottom", fontsize=6, color="0.4", style="italic")
        outputs = _savefig(fig, out_dir, "student_comparison")

    header = ["DR level"] + [label for label, _ in arms] + ["survival % (TCN/GRU/teacher)"]
    rows = []
    for lvl in DR_LEVELS:
        surv_cell = "/".join(f"{survival[label][lvl]:.1f}" for label, _ in arms)
        rows.append([lvl] + [f"{results[label][lvl]:.4f}" for label, _ in arms] + [surv_cell])
    csv_path = os.path.join(out_dir, "student_comparison.csv")
    _write_csv(csv_path, header, rows)
    tex_header = ["DR level"] + [label for label, _ in arms]
    tex_rows = [[lvl] + [f"{results[label][lvl]:.3f}" for label, _ in arms] for lvl in DR_LEVELS]
    tex_path = os.path.join(out_dir, "student_comparison.tex")
    _write_latex_table(
        tex_path,
        caption=(
            "Deployed student encoder comparison: attitude-norm steady-state tracking "
            r"error (degrees, lower is better) for TCN and GRU/C3 partial-observation "
            r"students against the full-state teacher (\texttt{model\_9998}) anchor. "
            "GRU has lower ss\\_error than TCN at every DR level; both students trail "
            "the full-state teacher, as expected from the reduced observation. "
            "Single-seed (seed 42) screening observation, not a statistical test."
        ),
        label="tab:student_comparison",
        header=tex_header,
        rows=tex_rows,
    )
    outputs += [os.path.basename(csv_path), os.path.basename(tex_path)]

    manifest_path = _write_manifest(
        out_dir,
        source_files,
        outputs,
        caveats=[
            "Single seed (42) per arm -- a screening comparison, not a statistical test; "
            "no cross-seed variance is available for TCN vs. GRU.",
            "The teacher arm is a full-state anchor, not a peer baseline: it has no "
            "partial-observation encoder, so its lower error is an upper bound on what "
            "encoding-induced degradation the students pay, not evidence about TCN vs. GRU "
            "encoder quality by itself.",
            "hard-level TCN/GRU both show 1 of 64 envs failing to survive (98.4%) while the "
            "teacher survives 64/64 -- their hard-level ss_error_std is inflated by that "
            "excursion (see source summary.json), so the hard-level point estimate is "
            "noisier than none/soft/medium.",
        ],
        extra={"axis": axis, "field": field, "seed": 42},
    )
    print(f"[student-comparison] wrote {len(outputs)} files to {out_dir}")
    print(f"[student-comparison] manifest: {manifest_path}")


COMMANDS = {
    "fault-ablation": cmd_fault_ablation,
    "teacher-summary": cmd_teacher_summary,
    "doraemon-curriculum": cmd_doraemon_curriculum,
    "student-comparison": cmd_student_comparison,
}


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    for name in COMMANDS:
        sp = sub.add_parser(name)
        if name == "doraemon-curriculum":
            sp.add_argument("--generate-if-missing", action="store_true",
                             help="invoke analyze_training.py --deep via /isaac-sim/python.sh if the source PNG is absent")
    sub.add_parser("all")
    args, unknown = p.parse_known_args()

    if args.cmd == "all":
        # re-parse each subcommand with defaults (doraemon-curriculum defaults to
        # NOT generating -- reuse existing output only, per task instructions).
        ns = argparse.Namespace(generate_if_missing=False)
        for name, fn in COMMANDS.items():
            print(f"\n=== {name} ===")
            try:
                fn(ns)
            except FileNotFoundError as e:
                print(f"[{name}] SKIPPED: {e}")
        return

    COMMANDS[args.cmd](args)


if __name__ == "__main__":
    main()
